### ISSUE TITLE
[FEAT]: implement logic for dashboard sidemenu toggling

### ISSUE THREAD

**Issue by ixahmedxi** [noodle-run/noodle#280]
![CleanShot 2023-08-06 at 00 17 10@2x](https://github.com/ixahmedxi/noodle/assets/20271968/3d0459d2-8a4c-4079-a553-c36ff7950598)

We currently have a sidemenu toggle button but it does nothing for now, we want it so that when the button is pressed, the following happens:

- it toggles the side menu open/close with a nice animation (preferably sliding effect)
- it changes the icon based on the state (so close panel icon when the sidemenu is open and open panel icon when the sidemenu is closed)

**Comment by gedeondoescode** [comment]
I can try and take this on this upcoming week

**Comment by nkilm** [comment]
@ixahmedxi I'd like to work on this issue.

**Comment by TheNatkat** [comment]
if this feature is still pending i can do that

**Comment by AJonastech** [comment]
Hi is this feature still pending ?
