### ISSUE TITLE
[BUG] User profile popup text color

### ISSUE THREAD

**Issue by alexdefender** [noodle-run/noodle#297]
**Describe the bug**
When clicking on the user profile on the light theme, the color of the text is white.

**Screenshots**
![Preview](https://i.postimg.cc/bwN9YjZs/2023-08-21-15-39-03.png)

I fixed it and created a pr https://github.com/ixahmedxi/noodle/pull/298. If you need help with development or some fixes, please, write me.

**Comment by sharathkumar55** [comment]
Hi @alexdefender can i work on this issue to start my open source contribution

**Comment by alexdefender** [comment]
@sharathkumar55 Hi! I fixed it https://github.com/ixahmedxi/noodle/pull/298

**Comment by sharathkumar55** [comment]
@alexdefender is there any other bugs i can work upon to start my open source contribution.If there please assign to me.
