### ISSUE TITLE
[BUG] OpenWeather API Key not defined

### ISSUE THREAD

**Issue by nateemerson** [noodle-run/noodle#299]
**Describe the bug**
During initial setup (following instructions from `CONTRIBUTING.md` I hit the following error when running the dev server for the first time:

```
@noodle/web: > next dev
@noodle/web: ❌ Invalid environment variables: { OPENWEATHER_API_KEY: [ 'Required' ] }
@noodle/web: - error Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
```

**To Reproduce**
Follow first run steps in `CONTRIBUTING.md`, run development server after installing dependencies.

**Expected behavior**
Development server starts running

**Screenshots**
<img width="971" alt="image" src="https://github.com/ixahmedxi/noodle/assets/596293/a1b427b2-0019-4ace-a0dd-4237b2ebd8e8">

**Information (please complete the following information):**

- Node v.18.15.0
- Pnpm v.8.6.11

**Additional context**

**Comment by nateemerson** [comment]
Simplest solution would likely be to add `OPENWEATHER_API_KEY` to `.env.example` and the `CONTRIBUTING.md` first run guide so that users are aware and the variable exists. However, while setting up I noticed the first run already requires quite a bit of service signups and keys to get things running...it may be convenient to add a mechanism to disable/stub the weather bit in case someone doesn't want to register for an open weather API key (which has more requirements and restrictions than other services...). That way a user can simply disable the weather info if they want to skip the API registration

**Comment by ixahmedxi** [comment]
I will actually switch to one that doesn't require any API key :)
