### ISSUE TITLE
Where to find a project roadmap?

### ISSUE THREAD

**Issue by mrgoonie** [noodle-run/noodle#303]
I think this project is interesting and would like to contribute, but when I forked it, seems there are nothing finished yet but authentication part. 

Is there a project roadmap?

**Comment by SebasQuirogaUCP** [comment]
`GitHub Projects` seems to be a very good option for this, it will help organize contributions flow in a very convenient  _tickets_ manner.

**Comment by Erb3** [comment]
See #327 "Roadmap to MVP"
