### ISSUE TITLE
Create notebooks table in the database

### ISSUE THREAD

**Issue by ixahmedxi** [noodle-run/noodle#308]
One of the core functionalities of Noodle is to be able to create notebooks and write notes for a module, and so with this we will need to create a `Notebook` table in the database that has a one to many relationship with a given module.

The columns:

- Id (UUID unique)
- userId (optional, could be null in the case of an orgId being there)
- orgId (optional, could be null in the case of a userId being there)

- title
- icon
- content

- lastEdited
- createdAt

- moduleId, this will be a link (one-to-many) to a module, where we will store the moduleId in every notebook instance

**Comment by s0ham075** [comment]
Hey can I work on this issue?
