### ISSUE TITLE
✨ Contribute to Noodle

### ISSUE THREAD

**Issue by ixahmedxi** [noodle-run/noodle#326]
Hello everyone, it has been quiet for a while now here on this repository, you might have thought that the project was abandoned but that was far from the truth. What was happening is that I started on a new codebase with minimal fuss to just let me get to my coding objectives faster, what I realised is that the complex structure that once was there, with packages, monorepo, caching, many tools...etc was only slowing me down and not taking us to that private beta phase sooner.

I have been working on the new codebase ever since in private, and from today I'm happy to share it publicly as well as define what is happening with the project going forward.

I have realised that the success of this project relies on me taking a more managerial position, I need to facilitate the opportunity for people to contribute and play a part in this project as much as I do, I can't do this alone, it would take forever, and so from now my approach with the project is to take a more supportive role in building a community around this project to aid its development.

And so with that said, I am 🚨 publicly announcing that there will be a Noodle core team, you can also call it noodlers, bowls...I guess we can decide that together. Basically anyone who would like to play a part in the development of this project is absolutely welcomed to. I would recommend joining our [Discord Server](https://discord.gg/ej3yMNqkmG) and let's have a discussion about your contributions!

Also with this announcement, I am also stating that Noodle will always dedicate a certain % of the revenue towards open source sponsorship, this includes Noodle core team and essential packages that we depend upon. Obviously we aren't making any money now or soon but hopefully we can get to that stage. Also a final note is that once we do release, Noodle core members will receive a free subscription to the platform as a thank you for their efforts.

I'm excited about the future of this project and sorry for being slow with it, life is a bit unpredictable and we're swimming in unfamiliar territory so it takes time to find stuff out and tune our workflows.

Let me know if you're interested!

**Comment by nicookenny** [comment]
This project is exactly what I have been looking for for a long time as a student, and having the opportunity to collaborate in building a product of this nature (and using it too hehe) is something that motivates me a lot. Here we'll be at the ready to give it our all 🔥

**Comment by kevinroosey** [comment]
Hey Ahmed! I'd love to help contribute! I'm currently in my third year at Depaul University in Chicago so this would be fun to use and fun to help build!

**Comment by RUGMJ** [comment]
I'd love to contribute to this project, like others this has been something missing from my student tools.

**Comment by ixahmedxi** [comment]
Please join the discord server and message me in the #contributing channel and we can align together!

**Comment by herropaul** [comment]
I just messaged on noodles discord, hoping we can collaborate soon :D

**Comment by asrvd** [comment]
im all in !

**Comment by madthax** [comment]
I'm in!

**Comment by niikkhilsharma** [comment]
This project looks really awesome and is absolutely perfect for someone who is looking to learn a lot many things. 😊🚀
I'll also be looking forward to contribute to this repository. 👀🤝

**Comment by Erb3** [comment]
> This project looks really awesome and is absolutely perfect for someone who is looking to learn a lot many things. 😊🚀 I'll also be looking forward to contribute to this repository. 👀🤝

@niikkhilsharma Happy to hear you are interested in the project, however noodle is currently on hold. I quote the following message from the noodle discord server by Ahmed Elsakaan:

> Hello everyone, I would just like to let you know that I have abandoned working on Noodle for the meantime. I know I have been really really inactive here and that's my fault, but I have basically burnt out from the project and decided to not pursue it further at the current time. Thank you all for your amazing support and interest in the project ❤️
