### ISSUE TITLE
[BUG] No loading icon on create module button

### ISSUE THREAD

**Issue by BlueZeeKing** [noodle-run/noodle#330]
**Describe the bug**
When creating a new module the button does not change to show a loading state. This can lead to confusion and the user clicking the button multiple times.

**To Reproduce**
Create a new module with a slow internet (use network throttling in chrome dev tools if needed)

**Expected behavior**
The button should show a loading icon

**Screenshots**
<img width="131" alt="Screenshot 2023-10-26 at 12 16 47 PM" src="https://github.com/ixahmedxi/noodle/assets/52867955/6b8d2540-76bf-4e24-9106-d0636a34da70">
What a loading button should look like with NextUI

**Information (please complete the following information):**

- Node version [e.g. 18.17.0] v18.18.2
- Pnpm version [e.g. 8.9.2] 8.9.2

**Additional context**
Sorry for not creating this issue before submitting a PR

**Comment by BlueZeeKing** [comment]
Completed by #329

**Comment by keshav-gupta19** [comment]
Is the issue solved or can i work on this??

**Comment by BlueZeeKing** [comment]
> Is the issue solved or can i work on this??

It is solved, just waiting to be merged in #329
