### ISSUE TITLE
Document using a local redis instead of Upstash

### ISSUE THREAD

**Issue by Erb3** [noodle-run/noodle#331]
**Is your feature request related to a problem? Please describe.**
When selfhosting, one may want to use a local redis instance instead of Upstash. It works flawlessly to host a redis server (or redis API compatible), and setting the `UPSTASH_REDIS_REST_URL` to `127.0.0.1`, or the IP of the redis instance. The `UPSTASH_REDIS_REST_TOKEN` can be left empty, but you need to update `src/env.mjs` to allow the `UPSTASH_REDIS_REST_TOKEN` to be empty.

```ts
UPSTASH_REDIS_REST_TOKEN: z.string().min(0),
```

**Describe the solution you'd like**
I would like `CONTRIBUTING.md` to document the usage of a local redis instance.

**Describe alternatives you've considered**
A different solution would be to make redis optional, since it is only used for rate limiting. If noodle is only exposed to LAN, rate limiting is not a big concern.

**Additional context**
See [Discord conversation](https://discord.com/channels/978718790177153054/1127308051658051674/1166801457580888085) about redis.

**Comment by YoussefLaunchUp** [comment]
I would love to see Redis made optional as well. Would make development easier.

**Comment by YoussefLaunchUp** [comment]
This PR has look at this plus just making it fully optional.
https://github.com/ixahmedxi/noodle/pull/333

**Comment by Erb3** [comment]
Fixed in #333
