### ISSUE TITLE
Explore the idea of using Bun as the package manager

### ISSUE THREAD

**Issue by ixahmedxi** [noodle-run/noodle#345]
We are currently using pnpm as our package manager, but Bun seems like the fastest solution available right now and as a believer of the Bun project, it would be cool to start using it just as our package manager.

Checks:

- [ ] `bun install` works.
- [ ] `bun run build` builds the project successfully.
- [ ] `bun typecheck` produces no type-errors.
- [ ] Update GitHub CI workflow to use bun instead of volta.
- [ ] Update our contributing guide to reflect this change.

**Comment by xhayper** [comment]
Will be doing the first three task.
