### ISSUE TITLE
Wrong timezone used

### ISSUE THREAD

**Issue by xhayper** [noodle-run/noodle#349]
**Describe the bug**
The timezone used in the app is wrong

**To Reproduce**
- Set your timezone to anything but UK
- Create a module
- Go to module page

**Expected behavior**
Should show that i was created a moment ago.

**Screenshots**
<img width="213" alt="Screenshot 2023-11-03 at 14 20 36" src="https://github.com/noodle-run/noodle/assets/46065349/e0c8917b-d352-4798-8c64-0758e3d97e2f">

**Information (please complete the following information):**

- Node version 18.18.2
- Bun version 1.0.8

**Additional context**

**Comment by Yashwanth-Chandrakumar** [comment]
I am currently working to resolve the bug thank you.
