### ISSUE TITLE
Maintenance: update packages to latest version

### ISSUE THREAD

**Issue by ixahmedxi** [noodle-run/noodle#350]
We need to upgrade to stuff like nextjs v14 and other packages, you can use npm-check-updates to check for new versions and apply them to the repository.

**Note 1**: the tanstack update is tied to tRPC, if tRPC supports tanstack query v5 then we can update that, otherwise we can't.

**Comment by MrBlackGhostt** [comment]
@ixahmedxi can you assign this issue #350 to me i love to contribute to noodle

**Comment by Erb3** [comment]
Might've been fixed in #361
