### ISSUE TITLE
Thoughts on future development of noodle

### ISSUE THREAD

**Issue by leecheeyong** [noodle-run/noodle#357]
First, I'd like to appreciate every contributors of this project, its really cool to solve issues that every students have. I have a few idea that I think should be added into noodle, they're not very necessary but would be awesome to have.

1. **Finance Feature**
As a student, I often experience financial issues, not lack of money, but didn't know how much I've spent on something, at school, for someone's birthday present, and .etc 
My idea is to have a template or module where users can make their own financial report that is easy for visualizing, for them to understand how much they've spent. We've had some discussions in the Discord server which we've talked about implementing bank's transaction history integration and so on but I felt like easing on keying in and recording payments is the most crucial thing. 
Learning how to manage financial stuff as a student is very important, and having a financial report for ourselves is of course the first step to become financial mastery. I felt like this feature doesn't have to be too complicated, and below is the concept of mine:

<img width="1440" alt="image" src="https://github.com/noodle-run/noodle/assets/81070048/657a811e-5b90-4955-8c40-4edce402ea3c">

2. **API Integration**
API endpoints, integration for services like Slack, WhatsApp, Telegram, Discord Webhook and .etc
- They can be used for notifications (e.g. reminders)
- Keep track of statuses 
- Developer friendly API endpoints for people like us to integrate noodle in our apps

3. **Connections and sharing**
- Able to share notebooks with friends to collaborate
- Username system for ease
- Able to embed pages (iframe)

4. **Funds**
- Simple payment using stripe (easy to integrate), to support the developers, get access to exclusive features
- Pay to unlock customizing features (e.g background design)

Hopefully some of my ideas could be take into consideration in the future, and I'm really looking forward into the financial feature. What do you all think? Feel free to leave your ideas and thoughts below !

**Comment by betula** [comment]
Great idea but no time)) It's usually case for every giant projects. This repo it's only preview and good preformed idea, but no real development activity here. Probably it will be done never.

If someone wants to be challenge this idea, someone who have a fund  or ideas of way of funding, it will be great step for all over humanity!
