### ISSUE TITLE
Add The fincance

### ISSUE THREAD

**Issue by janareddyc7** [noodle-run/noodle#360]
I would like to contribute to this project by adding the Finance Feature suggested by leecheeyoung  I can finish the feauture but the probelm is when i clone the repostory add the changes how do i commit it back ._

**Comment by Erb3** [comment]
See #347, a finance tab would probably not get merged.

To contribute, you fork the repository, clone it to your machine, do your changes, commit, and push. Once you visit the repository again you will see a button that says "Contribute". There are a lot of guides out there on how to use git 😃

**Comment by janareddyc7** [comment]
thanks
