### ISSUE TITLE
Add actual users name / email to dashboard welcome message

### ISSUE THREAD

**Issue by dickeyy** [noodle-run/noodle#372]
**Is your feature request related to a problem? Please describe.**
When the user goes to the dashboard, they should be welcomed by their name/email.

**Describe the solution you'd like**
When the user goes to /app, it should say "Welcome {user.firstName}" or "Welcome {user.emailAddresses[0].emailAddress}"

**Describe alternatives you've considered**
I mean, no welcome message I guess?

**Additional context**
I've implemented the fix for this already. I would like feedback before submitting a PR. here is what it looks like 

<img width="1491" alt="image" src="https://github.com/user-attachments/assets/493cb63a-448d-49c6-b50a-cd86b38209cf">

**Comment by Erb3** [comment]
I feel like it should prioritize like following:
1. first name
2. if email includes a dot, use what comes before the dot (`john.doe@example.com` becomes `john`)
3. otherwise use everything before the @ (`johndoe@example.com` becomes `johndoe`)

**Comment by ixahmedxi** [comment]
Yeah I like @Erb3's idea here.

**Comment by MUK-Dev** [comment]
HI, is this issue up for grabs?

**Comment by dickeyy** [comment]
#375
