### ISSUE TITLE
feat: add icons search bar to module creation popover

### ISSUE THREAD

**Issue by ixahmedxi** [noodle-run/noodle#382]
Right now, the module creation popover's icon selection doesn't have any way of filtering through the huge list of icons into ones that you want, making it very hard to find the icon that you want.

![{6CFE2420-D521-484B-9B31-3033CB2592C8}](https://github.com/user-attachments/assets/184ae7b2-c9fb-45cf-8201-67ccda45e654)

We probably then need a search input bar above the grid of icons for this. We already have the `Input` primitive so should be able to utilise that for the search box and then hooking it up to filter down the list of icons based on it's value.

**Comment by khanhadi** [comment]
Hi! I'd like to have a go at this one.
